create table if not exists public.dealzy_user_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.dealzy_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dealzy_saved_deals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  deal_key text not null,
  deal_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(user_id, deal_key)
);

create table if not exists public.dealzy_trips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  starts_on date,
  ends_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dealzy_trip_items (
  id bigint generated by default as identity primary key,
  trip_id uuid not null references public.dealzy_trips(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  deal_key text,
  item_data jsonb not null default '{}'::jsonb,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.dealzy_alerts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  query text not null,
  max_price numeric,
  radius_miles numeric,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.dealzy_price_watches (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  target_price numeric,
  source_url text,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.dealzy_coupons (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  merchant text not null,
  code text not null,
  expires_on date,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.dealzy_user_data enable row level security;
alter table public.dealzy_profiles enable row level security;
alter table public.dealzy_saved_deals enable row level security;
alter table public.dealzy_trips enable row level security;
alter table public.dealzy_trip_items enable row level security;
alter table public.dealzy_alerts enable row level security;
alter table public.dealzy_price_watches enable row level security;
alter table public.dealzy_coupons enable row level security;

drop policy if exists "Users can read own Dealzy data" on public.dealzy_user_data;
create policy "Users can read own Dealzy data" on public.dealzy_user_data
for select using ((select auth.uid()) = user_id);
drop policy if exists "Users can insert own Dealzy data" on public.dealzy_user_data;
create policy "Users can insert own Dealzy data" on public.dealzy_user_data
for insert with check ((select auth.uid()) = user_id);
drop policy if exists "Users can update own Dealzy data" on public.dealzy_user_data;
create policy "Users can update own Dealzy data" on public.dealzy_user_data
for update using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "dealzy_profiles_own" on public.dealzy_profiles;
create policy "dealzy_profiles_own" on public.dealzy_profiles
for all using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "dealzy_saved_deals_own" on public.dealzy_saved_deals;
create policy "dealzy_saved_deals_own" on public.dealzy_saved_deals
for all using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "dealzy_trips_own" on public.dealzy_trips;
create policy "dealzy_trips_own" on public.dealzy_trips
for all using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "dealzy_trip_items_own" on public.dealzy_trip_items;
create policy "dealzy_trip_items_own" on public.dealzy_trip_items
for all using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "dealzy_alerts_own" on public.dealzy_alerts;
create policy "dealzy_alerts_own" on public.dealzy_alerts
for all using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "dealzy_price_watches_own" on public.dealzy_price_watches;
create policy "dealzy_price_watches_own" on public.dealzy_price_watches
for all using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "dealzy_coupons_own" on public.dealzy_coupons;
create policy "dealzy_coupons_own" on public.dealzy_coupons
for all using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create index if not exists idx_dealzy_saved_deals_user on public.dealzy_saved_deals(user_id);
create index if not exists idx_dealzy_trips_user on public.dealzy_trips(user_id);
create index if not exists idx_dealzy_trip_items_user on public.dealzy_trip_items(user_id);
create index if not exists idx_dealzy_trip_items_trip on public.dealzy_trip_items(trip_id);
create index if not exists idx_dealzy_alerts_user on public.dealzy_alerts(user_id);
create index if not exists idx_dealzy_price_watches_user on public.dealzy_price_watches(user_id);
create index if not exists idx_dealzy_coupons_user on public.dealzy_coupons(user_id);


create table if not exists public.dealzy_price_history (
  id bigint generated by default as identity primary key,
  provider text not null,
  deal_key text not null,
  title text,
  price numeric not null,
  old_price numeric,
  currency text not null default 'USD',
  source_url text,
  observed_at timestamptz not null default now(),
  user_id uuid references auth.users(id) on delete cascade
);
alter table public.dealzy_price_history enable row level security;
drop policy if exists "dealzy_price_history_own" on public.dealzy_price_history;
create policy "dealzy_price_history_own" on public.dealzy_price_history
for all using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create index if not exists idx_dealzy_price_history_user_key_time
on public.dealzy_price_history(user_id, provider, deal_key, observed_at desc);

create table if not exists public.dealzy_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null default 'deal',
  title text not null,
  body text not null,
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  dedupe_key text
);
alter table public.dealzy_notifications enable row level security;
drop policy if exists "dealzy_notifications_own" on public.dealzy_notifications;
create policy "dealzy_notifications_own" on public.dealzy_notifications
for all using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create index if not exists idx_dealzy_notifications_user_time
on public.dealzy_notifications(user_id, created_at desc);
create unique index if not exists uq_dealzy_notifications_user_dedupe
on public.dealzy_notifications(user_id, dedupe_key) where dedupe_key is not null;


create table if not exists public.dealzy_travel_searches (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null,
  search_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.dealzy_travel_searches enable row level security;
drop policy if exists "dealzy_travel_searches_own" on public.dealzy_travel_searches;
create policy "dealzy_travel_searches_own" on public.dealzy_travel_searches
for all using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create index if not exists idx_dealzy_travel_searches_user_time
on public.dealzy_travel_searches(user_id, created_at desc);


alter table public.dealzy_alerts add column if not exists client_key text;
alter table public.dealzy_price_watches add column if not exists client_key text;
alter table public.dealzy_coupons add column if not exists client_key text;
alter table public.dealzy_travel_searches add column if not exists client_key text;

create unique index if not exists uq_dealzy_alerts_user_client
on public.dealzy_alerts(user_id, client_key) where client_key is not null;
create unique index if not exists uq_dealzy_price_watches_user_client
on public.dealzy_price_watches(user_id, client_key) where client_key is not null;
create unique index if not exists uq_dealzy_coupons_user_client
on public.dealzy_coupons(user_id, client_key) where client_key is not null;
create unique index if not exists uq_dealzy_travel_searches_user_client
on public.dealzy_travel_searches(user_id, client_key) where client_key is not null;
