plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dealzy.ai'
    compileSdk 35

    defaultConfig {
        applicationId 'com.dealzy.ai.test16'
        minSdk 24
        targetSdk 35
        versionCode 16
        versionName '1.6-android-back-nav'
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
