plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dealzy.ai'
    compileSdk 35

    defaultConfig {
        applicationId 'com.dealzy.ai.test4'
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName '0.4-nav-active-fix'
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
